services:
  app:
    build: ./backend
    image: spp-backend
    container_name: spp-backend
    depends_on:
      - postgres
      - init-images
    volumes:
      - ./backend:/app
      - maven-repo:/root/.m2
      - images:/images
    working_dir: /app
    env_file:
      - .env
      - .env.${SPRING_PROFILES_ACTIVE:-dev}
    ports:
      - "${SPRING_APP_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SPRING_DEVTOOLS_REMOTE_DEBUG_ENABLED: "true"
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
      SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS: "/app/src"
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - project-network

  postgres:
    image: postgres:16
    container_name: spp-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
      - .env.${SPRING_PROFILES_ACTIVE:-dev}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - project-network

  init-images:
    image: alpine
    command: >
      sh -c "cp -R /seed/* /images/"
    volumes:
      - images:/images
      - ./seed-images:/seed

volumes:
  maven-repo:
  postgres_data:
  images:

networks:
  project-network:
    driver: bridge