services:
  app:
    build: ./backend
    image: spp-backend
    container_name: spp-backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - maven-repo:/root/.m2
    working_dir: /app
    env_file:
      - .env
      - .env.${SPRING_PROFILES_ACTIVE:-dev}
    ports:
      - "${SPRING_APP_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SPRING_DEVTOOLS_REMOTE_DEBUG_ENABLED: "true"
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
      SPRING_DEVTOOLS_RESTART_ADDITIONAL_PATHS: "/app/src"
    networks:
      - project-network

  postgres:
    image: postgres:16
    container_name: spp-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
      - .env.${SPRING_PROFILES_ACTIVE:-dev}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - project-network

volumes:
  maven-repo:
  postgres_data:

networks:
  project-network:
    driver: bridge