server {
    listen 80;
    server_name localhost;

    # Springboot API
    location /api/ {
        proxy_pass http://app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Static files
    location /image/ {
        alias /usr/share/nginx/images/;
    }
}