worker_processes  auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/conf.d/*.conf;

    client_max_body_size 50M;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    client_body_buffer_size 16K;
    client_header_buffer_size 4k;
    large_client_header_buffers 4 8k;

    access_log /dev/stdout;

    proxy_buffer_size 8k;
    proxy_buffers 8 16k;
    proxy_busy_buffers_size 24k;

    keepalive_timeout 65;
    keepalive_requests 10000;
}
