spring.application.name=backend
# default profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

# DevTools settings for hot reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=src/main/java,src/main/resources
spring.devtools.restart.exclude=static/**,public/**

# Flyway base settings
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Database connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Jackson settings
spring.jackson.property-naming-strategy=SNAKE_CASE

# JWT secret key
jwt.secret=${JWT_SECRET}
